version: '3.9'
services:
  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    networks: 
      - sendhooks
    ports:
      - "6379:6379"
  
  mongo:
    container_name: mongo
    image: mongo
    networks: 
      - sendhooks

  webhook-sender:
    container_name: webhook-sender
    build: ../webhook
    networks: 
      - sendhooks
    depends_on:
      - redis
    volumes:
      - ./config.json:/root/config.json

  flask-api:
    container_name: flask-api
    build: ../example-project/api
    networks: 
      - sendhooks
    ports:
      - "5001:5000"
    depends_on:
      - webhook-sender
  
  sendhooks-engine-api:
    container_name: sendhooks-engine-api
    build: .
    networks: 
      - sendhooks
    env_file:
      - ./.env
    ports:
      - "5002:5001"
    depends_on:
      - redis
      - mongo
      - webhook-sender
      - flask-api

networks:
  sendhooks:
  